# Site settings
title: Fractal
email: youremailaddress@gmail.com
description: Just a simple, single page responsive template brought to you by HTML5 UP.
baseurl: "/fractal-jekyll-theme" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
download_button_url: https://gitlab.com/andrewbanchich/fractal-jekyll-theme

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://gitlab.com/u/andrewbanchich
googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url:
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url:
slack_url:
twitter_url: https://twitter.com/andrewbanchich

# Build settings
markdown: kramdown
